const QUANTITY_CREATE_CARDS_START = 5;
const QUANTITY_CREATE_CARDS_STEP = 5;
const QUANTITY_CREATE_CARDS_EXTRA = 2;
const POPUP_SCROLL = 0;
const KeysClose = {
  ESC: 'Esc',
  ESCAPE: 'Escape',
};

export {
  QUANTITY_CREATE_CARDS_START,
  QUANTITY_CREATE_CARDS_STEP,
  QUANTITY_CREATE_CARDS_EXTRA,
  KeysClose,
  POPUP_SCROLL
};
